### ISSUE TITLE
Read config file in another location

### ISSUE THREAD

**Issue by Ivnst** [edpollitt/Nerdle.AutoConfig#6]
Hi,
Could you please add an ability to read configuration from not default configuration file?

For instance, it could look like this:
AutoConfig.SetPathToConfigFile(string configFile)
or like this
AutoConfig.Map<T>(string sectionName = null, string fileName = null)

Thanks!

**Comment by edpollitt** [comment]
I've added an optional string parameter (this avoids any synchronisation issues that could occur by setting a global override).

`AutoConfig.Map<MyConfig>(configFilePath: "blah.config");`

[v1.2.0 available on nuget now](https://www.nuget.org/packages/Nerdle.AutoConfig/)

Thanks for your interest in the library :)

**Comment by Ivnst** [comment]
Everything works perfectly! Thanks for so quick response!

**Comment by VMAtm** [comment]
Thanks for this update, you probably should add this to the docs
